# Generated by Django 3.2.9 on 2021-11-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='type',
        ),
        migrations.AddField(
            model_name='review',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='climb_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='difficulty',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
